---
title: "Draft"
author: "Adam Bartonicek"
date: "`r Sys.Date()`"
output: html_document
mainfont: "Liberation Serif"
fontcolor: "#1F271B"
backgroundcolor: "floralwhite"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Interactive vs. Dynamic Visualization

While "interactive data visualization" is a popular term, there seems to be little consensus as to what the titular "interactivity" means. For example, the R Graph Gallery page on Interactive charts (https://r-graph-gallery.com/interactive-charts.html) features several plots which allow for the following user interactions: zooming, panning, hovering, 3D rotation, and node repositioning in a network graph. Importantly, in all of the examples above, the interaction and its results take place within the same plot. In contrast, the plotly Dash documentation page on Interactive Visualizations (https://dash.plotly.com/interactive-graphing) features examples of linked hovering and cross-filtering, where the user's interaction within one plot propagates into another plot (e.g. selecting few points within a scatterplot highlights the same data rows in another). These two sets of examples represent fundamentally different types of interactivity. The first -- interaction within a single isolated plot -- requires only access to the data and manipulation of either the graphical attributes of the plot or the scales/coordinate system. The second -- interaction which propagates between plots -- requires an additional data structure that keeps track of which rows are currently selected. Furthemore, when there isn't a one-to-one relationship between the rows of the data and their graphical representation shown on screen -- when, for example, the height of a bar in a barplot represents a number of cases with the identical x-value -- then whatever statistical transformation underlies the graphical representation also needs to be recomputed every time new rows of data are selected.

::: column-page-inset
+----------------------------------+-------------------------+---------------------+--------------------+---------------------------------+--------------+
| Type                             | Representation          | Typical tasks       | Compute statistics | Requires                        | Complexity   |
+==================================+=========================+=====================+====================+=================================+==============+
| Truly interactive/ Communicating | -   One-to-one          | -   Brushing        | Often              | -   Data                        | High         |
|                                  | -   Many-to-one         | -   Linking         |                    | -   Graphical attributes        |              |
|                                  |                         | -   Cross-filtering |                    | -   Selected cases              |              |
|                                  |                         |                     |                    | -   Statistical transformations |              |
+----------------------------------+-------------------------+---------------------+--------------------+---------------------------------+--------------+
| Embarassingly interactive        | -   Strictly one-to-one | -   Brushing        | Never              | -   Data                        | Intermediate |
|                                  |                         | -   Linking         |                    | -   Graphical attributes        |              |
|                                  |                         | -   Cross-filtering |                    | -   Selected cases              |              |
+----------------------------------+-------------------------+---------------------+--------------------+---------------------------------+--------------+
| Dynamic                          | -   One-to-one          | -   Zooming         | Once               | -   Data                        | Low          |
|                                  | -   Many-to-one         | -   Panning         |                    | -   Graphical attributes        |              |
|                                  |                         | -   Hovering        |                    |                                 |              |
+----------------------------------+-------------------------+---------------------+--------------------+---------------------------------+--------------+

: Table 1: Interactive visualization types and their features
:::
